# Generated by Django 2.0.3 on 2018-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='年龄')),
                ('sex', models.IntegerField(blank=True, choices=[(1, '男'), (0, '女')], null=True, verbose_name='性别')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱地址')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
        ),
    ]
